version: "3.5"
services: 
  builder:
    build:
      context: ./images/builder
    ports:
       - "8080:8080"
    volumes: 
      - type: volume
        source: ./Config.properties
        target: /App42PaaS-Java-MySQL-Sample/WebContent/Config.properties
  
  db:
    image: mariadb:10.1
    environment: 
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - builder

volumes: 
  appdata:

