version: "3.7"
services: 
  builder:
    build:
      context: ./images/builder
    volumes: 
      - type: volume
        source: appdata
        target: /appdata
    command: sleep infinity
  
  prodworker:
    image: openjdk:8-jre-slim-buster
    depends_on:
      - builder
    volumes:
      - type: volume
        source: appdata
        target: /appdata
    command: java -jar /appdata/hello-world-1.0-SNAPSHOT.jar

volumes: 
  appdata:

