version: "3.7"
services: 
  builder:
    build:
      context: ./images/builder
    volumes: 
      - type: volume
        source: appdata
        target: /appdata
    command: cp hello-world-1.0-SNAPSHOT.jar /appdata
  
  prodworker:
    image: openjdk:8-jre-slim-buster
    volumes:
      - type: volume
        source: appdata
        target: /runjar
    depends_on:
      - builder
    command: ["java -jar /runjar/hello-world-1.0-SNAPSHOT.jar; sleep infinity"]

volumes: 
  appdata:

