version: "3.7"
services: 
  builder:
      build:
       context: .
       dockerfile: : ./images/builder
     working_dir: /var/app
     volumes: 
       - ./app/:var/app
     links:
       - prodworker
  
  prodworker:
    image: alpine:latest 
    volumes:
      - ./app/:var/app