version: "3.7"
services: 
  builder:
    build:
      context: ./images/builder
    volumes: 
      - type: volume
        source: appdata
        target: /appdata
    command: sleep infinity
  
  prodworker:
    image: openjdk:8-jre-slim-buster
    volumes:
      - type: volume
        source: appdata
        target: /runjar
    depends_on:
      - builder
    command: dir

volumes: 
  appdata:

