version: "3.7"
services: 
  builder:
     image: ubuntu:latest
     command: sh -c "apt update && apt install maven -y"
     working_dir: /var/app
     volumes: 
       - ./app/:var/app
     links:
       - prodworker
  
  prodworker:
    image: alpine:latest 
    volumes:
      - ./app/:var/app
    links:
      - builder