version: "3.5"
services: 
  builder:
    build:
      context: ./images/builder
    ports:
       - "8080:8080"
    volumes: 
      - type: volume
        source: ./Config.properties
        target: /usr/local/tomcat/ROOT/Config.properties
    links:
      - db
  
  db:
    image: mariadb:10.1
    container_name: db
    environment: 
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dbtest
    ports:
       - "3306:3306"

volumes: 
  appdata:

