version: "3.7"
services: 
  builder:
    build:
      context: ./images/builder
    volumes: 
      - type: bind
        source: ./app
        target: /app
  
  prodworker:
    image: alpine:latest
    depends_on:
      - builder
    volumes:
      - type: volume
        source: ./app
        target: /app

